-- This file is for informational purposes to show you the database structure.
-- I will set this up in Supabase for you once you complete the integration.

-- Table for "Our Values" section
CREATE TABLE values (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon_name TEXT NOT NULL, -- Name of the Lucide icon (e.g., "Award", "Users")
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  display_order INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for "Meet Our Team" section
CREATE TABLE team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  image_url TEXT, -- URL to the team member's photo
  description TEXT,
  display_order INT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for "Mission & Vision" content
CREATE TABLE company_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  info_key TEXT UNIQUE NOT NULL, -- e.g., "mission_statement", "vision_statement"
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  icon_name TEXT, -- Name of the Lucide icon (e.g., "Target", "Lightbulb")
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- You would then insert your data like this:
-- (This is just an example)

INSERT INTO values (icon_name, title, description, display_order) VALUES
('Award', 'Quality Excellence', 'We never compromise on quality. Every tile is carefully selected and tested to meet our high standards.', 1),
('Users', 'Customer First', 'Your satisfaction is our priority. We listen, understand, and deliver exactly what you envision.', 2);

INSERT INTO team_members (name, role, image_url, description, display_order) VALUES
('John Smith', 'Founder & CEO', 'https://example.com/john.jpg', 'With over 20 years in the tile industry, John founded Shubhaangan with a vision to transform spaces through quality craftsmanship.', 1),
('Sarah Johnson', 'Design Director', 'https://example.com/sarah.jpg', 'Sarah brings creative vision and technical expertise to every project, ensuring beautiful and functional results.', 2);

INSERT INTO company_info (info_key, title, content, icon_name) VALUES
('mission_statement', 'Our Mission', 'To transform spaces and enrich lives through premium quality Sheets, exceptional craftsmanship, and unparalleled customer service. We strive to make every project a masterpiece.', 'Target'),
('vision_statement', 'Our Vision', 'To be the leading tile company recognized for innovation, quality, and customer satisfaction. We envision a world where beautiful, functional spaces are accessible to everyone.', 'Lightbulb');